name: Build Angular Project
on: push
jobs:
  build-and-push:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install NPM dependencies
        run: npm install
      - name: Build Project assets
        run: npm run build:prod  # Assuming your build command is 'npm run build:prod'
      - name: Configure Git
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
      - name: Create Artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-files
          path: dist/physio-doc  # Adjust the path if your build output is in a different location

  deploy-to-gh-pages:  # Renamed for clarity
    needs: build-and-push  # This job depends on the build-and-push job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Artifact (check for successful build)
        uses: actions/download-artifact@v3
        with:
          name: built-files
          path: downloaded_files
      - name: Configure Git
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
      - name: Push build files to gh-pages (replace with your deployment steps)
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git push origin -d gh-pages
          git checkout -b gh-pages
          git rm -rf .
          cp -r downloaded_files/* .
          git rm -r downloaded_files
          git add .
          git commit -m "Push build files"
          git push origin gh-pages