name: Build Angular Project
on: push
jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install NPM dependencies
        run: npm install
      - name: Build Project assets
        run: npm run build:prod
      - name: Configure Git
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
      - name: Create Artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-files
          path: dist
      - name: Add Built files
        run: git add dist/
      - name: Commit Changes
        run: git commit -m "Push built files"
      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: git push origin gh-pages