name: Build Angular Project

on: push

jobs:
  build-and-push:
    name: Build project and deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install NPM dependencies
        run: npm install
      - name: Build Project assets
        run: npm run build:prod
      - name: Configure Git
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
      - name: switch branch
        run: git checkout -b gh-pages
      - name: Push build files to gh-pages (uses actions/checkout)
        uses: actions/checkout@v3  # Checkout the gh-pages branch  
        with:
          ref: gh-pages  # Specify the target branch
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Deploy built files (uses shell commands)
        run: |  # Separate step for deployment commands
          cp -r dist/physio-doc/* .  # Copy build files to root of gh-pages branch
          git add .
          git commit -m "Push build files"
          git push origin gh-pages